import type { Subject } from '../types/data/general-subject-id-data'

export const subjectLabels: Record<Subject, string> = {
  // Academic Subjects
  japanese: '国語',
  english: '英語',
  mathematics: '数学',
  science: '理科',
  physics: '物理',
  chemistry: '化学',
  biology: '生物',
  earth_science: '地学',
  social_studies: '社会',
  history: '歴史',
  geography: '地理',
  civics: '公民',
  economics: '経済',
  art: '美術',
  music: '音楽',
  physical_education: '体育',
  health: '保健',
  home_economics: '家庭科',
  technology: '技術',
  information: '情報',
  moral_education: '道徳',
  integrated_studies: '総合的な学習',

  // Languages
  chinese: '中国語',
  korean: '韓国語',
  french: 'フランス語',
  german: 'ドイツ語',
  spanish: 'スペイン語',
  italian: 'イタリア語',
  portuguese: 'ポルトガル語',
  russian: 'ロシア語',
  arabic: 'アラビア語',
  hindi: 'ヒンディー語',
  thai: 'タイ語',
  vietnamese: 'ベトナム語',

  // Tech
  programming: 'プログラミング',
  javascript: 'JavaScript',
  typescript: 'TypeScript',
  python: 'Python',
  java: 'Java',
  cpp: 'C++',
  csharp: 'C#',
  go: 'Go',
  rust: 'Rust',
  swift: 'Swift',
  kotlin: 'Kotlin',
  web_development: 'Web開発',
  mobile_development: 'モバイル開発',
  data_science: 'データサイエンス',
  machine_learning: '機械学習',
  ai: 'AI',
  database: 'データベース',
  system_design: 'システム設計',
  cybersecurity: 'サイバーセキュリティ',
  cloud_computing: 'クラウドコンピューティング',

  // Business
  business: 'ビジネス',
  marketing: 'マーケティング',
  sales: '営業',
  accounting: '会計',
  finance: '金融',
  management: '経営',
  leadership: 'リーダーシップ',
  project_management: 'プロジェクト管理',
  presentation: 'プレゼンテーション',
  negotiation: '交渉術',
  entrepreneurship: '起業',
  investment: '投資',
  real_estate: '不動産',
  insurance: '保険',
  consulting: 'コンサルティング',

  // Life Skills
  cooking: '料理',
  cleaning: '掃除',
  gardening: 'ガーデニング',
  diy: 'DIY',
  budgeting: '家計管理',
  time_management: '時間管理',
  organization: '整理整頓',
  communication: 'コミュニケーション',
  public_speaking: 'パブリックスピーキング',
  writing: '文章作成',
  reading: '読書',
  critical_thinking: '批判的思考',
  problem_solving: '問題解決',

  // Health
  exercise: '運動',
  yoga: 'ヨガ',
  meditation: '瞑想',
  nutrition: '栄養学',
  mental_health: 'メンタルヘルス',
  sleep: '睡眠',
  stress_management: 'ストレス管理',
  weight_training: '筋トレ',
  cardio: '有酸素運動',
  stretching: 'ストレッチ',
  walking: 'ウォーキング',
  running: 'ランニング',
  swimming: '水泳',
  cycling: 'サイクリング',

  // Hobbies
  drawing: '絵画・デッサン',
  painting: '絵画',
  photography: '写真',
  video_editing: '動画編集',
  graphic_design: 'グラフィックデザイン',
  writing_creative: '創作活動',
  blogging: 'ブログ',
  journaling: '日記',
  crafting: '手芸',
  knitting: '編み物',
  woodworking: '木工',
  pottery: '陶芸',
  calligraphy: '書道',
  origami: '折り紙',

  // Music
  piano: 'ピアノ',
  guitar: 'ギター',
  violin: 'バイオリン',
  drums: 'ドラム',
  bass: 'ベース',
  saxophone: 'サックス',
  flute: 'フルート',
  trumpet: 'トランペット',
  singing: '歌唱',
  music_theory: '音楽理論',
  composition: '作曲',
  music_production: '音楽制作',

  // Sports
  soccer: 'サッカー',
  basketball: 'バスケットボール',
  baseball: '野球',
  tennis: 'テニス',
  volleyball: 'バレーボール',
  badminton: 'バドミントン',
  table_tennis: '卓球',
  golf: 'ゴルフ',
  martial_arts: '武道',
  boxing: 'ボクシング',
  swimming_sport: '競泳',
  track_field: '陸上競技',
  skiing: 'スキー',
  snowboarding: 'スノーボード',

  // Certifications
  toeic: 'TOEIC',
  toefl: 'TOEFL',
  eiken: '英検',
  jlpt: '日本語能力試験',
  ielts: 'IELTS',
  cpa: '公認会計士',
  fp: 'ファイナンシャルプランナー',
  it_passport: 'ITパスポート',
  basic_information_technology: '基本情報技術者',
  applied_information_technology: '応用情報技術者',
  aws: 'AWS認定',
  google_cloud: 'Google Cloud認定',
  azure: 'Microsoft Azure認定',
  pmp: 'PMP',
  scrum_master: 'スクラムマスター',
}
